version: '2'
services:
  web:
    build: ./web
    ports:
     - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:somepass@db:5432/mydb
    volumes:
     - ./web/src/server:/app/server
     - ./web/src/app:/app/app
     - ./web/data/public:/app/public
     - ./web/data/node_modules:/app/node_modules
    command: gulp dev
  db:
    image: "postgres:9.4"
    environment:
      - POSTGRES_PASSWORD=somepass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    volumes:
      - ./db/data:/var/lib/postgresql/data